//go:build ignore

// Command gen builds tables.go from the Unicode Character Database and the
// UTS #39 security data.
//
// Run it with:
//
//	go run gen.go
//
// It downloads the five source files from unicode.org, so it needs network
// access. The generated tables are committed, so building and testing the
// package does not.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

// unicodeVersion is the UCD release the tables are generated from. The
// security data files carry a "# Version:" header that must match it; a
// mismatch is a hard failure rather than a silently mixed table.
const unicodeVersion = "17.0.0"

const (
	ucdBase      = "https://www.unicode.org/Public/" + unicodeVersion + "/ucd/"
	securityBase = "https://www.unicode.org/Public/security/latest/"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen: ")

	aliases := fetch(ucdBase + "PropertyValueAliases.txt")
	scripts := fetch(ucdBase + "Scripts.txt")
	scriptExt := fetch(ucdBase + "ScriptExtensions.txt")
	idStatus := fetch(securityBase + "IdentifierStatus.txt")

	checkVersion("IdentifierStatus.txt", idStatus)

	codes, longToCode := parseAliases(aliases)
	// Hanb, Jpan and Kore are ISO 15924 codes for writing systems, not
	// Script property values. UTS #39 section 5.1 adds them to augmented
	// script sets, so they need indices of their own.
	codes = append(codes, "Hanb", "Jpan", "Kore")

	index := make(map[string]int, len(codes))
	for i, c := range codes {
		index[c] = i
	}

	base := parseScripts(scripts, longToCode)
	ext := parseScriptExtensions(scriptExt)

	words := (len(codes) + 63) / 64
	all := make([]uint64, words)
	for i := range codes {
		all[i/64] |= 1 << uint(i%64)
	}

	augmented := func(r rune) []uint64 {
		scx, ok := ext[r]
		if !ok {
			sc, ok := base[r]
			if !ok {
				sc = "Zzzz" // Scripts.txt @missing default is Unknown.
			}
			scx = []string{sc}
		}
		// "Sets containing Zyyy (Common) or Zinh (Inherited) are treated as
		// ALL, the set of all script values."
		for _, s := range scx {
			if s == "Zyyy" || s == "Zinh" {
				return append([]uint64(nil), all...)
			}
		}
		set := make([]uint64, words)
		add := func(code string) {
			i, ok := index[code]
			if !ok {
				log.Fatalf("unknown script code %q", code)
			}
			set[i/64] |= 1 << uint(i%64)
		}
		has := func(code string) bool {
			for _, s := range scx {
				if s == code {
					return true
				}
			}
			return false
		}
		for _, s := range scx {
			add(s)
		}
		// The five augmentation rules of UTS #39 section 5.1.
		if has("Hani") {
			add("Hanb")
			add("Jpan")
			add("Kore")
		}
		if has("Hira") {
			add("Jpan")
		}
		if has("Kana") {
			add("Jpan")
		}
		if has("Hang") {
			add("Kore")
		}
		if has("Bopo") {
			add("Hanb")
		}
		return set
	}

	// Walk every code point once and coalesce runs that share a set. This is
	// slower than merging the two range tables but it cannot get the overlap
	// between Scripts.txt and ScriptExtensions.txt wrong.
	type entry struct {
		lo, hi rune
		set    int
	}
	var pool [][]uint64
	poolIndex := make(map[string]int)
	intern := func(set []uint64) int {
		key := fmt.Sprint(set)
		if i, ok := poolIndex[key]; ok {
			return i
		}
		i := len(pool)
		pool = append(pool, set)
		poolIndex[key] = i
		return i
	}

	var entries []entry
	for r := rune(0); r <= 0x10FFFF; r++ {
		if r == 0xD800 {
			r = 0xDFFF // surrogates: leave them at the Unknown default
		}
		id := intern(augmented(r))
		if n := len(entries); n > 0 && entries[n-1].set == id && entries[n-1].hi == r-1 {
			entries[n-1].hi = r
			continue
		}
		entries = append(entries, entry{lo: r, hi: r, set: id})
	}

	allowed := parseAllowed(idStatus)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package scriptset\n\n")
	fmt.Fprintf(&buf, "// UnicodeVersion is the UCD and UTS #39 security-data release these\n")
	fmt.Fprintf(&buf, "// tables were generated from.\n")
	fmt.Fprintf(&buf, "const UnicodeVersion = %q\n\n", unicodeVersion)
	fmt.Fprintf(&buf, "const numScripts = %d\n", len(codes))
	fmt.Fprintf(&buf, "const setWords = %d\n\n", words)

	fmt.Fprintf(&buf, "// Script codes, in ISO 15924 form.\nconst (\n")
	for i, c := range codes {
		fmt.Fprintf(&buf, "\t%s Script = %d\n", c, i)
	}
	fmt.Fprintf(&buf, ")\n\n")

	fmt.Fprintf(&buf, "var scriptNames = [numScripts]string{\n")
	for _, c := range codes {
		fmt.Fprintf(&buf, "\t%q,\n", c)
	}
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "var setPool = [...][setWords]uint64{\n")
	for _, set := range pool {
		fmt.Fprintf(&buf, "\t{")
		for i, w := range set {
			if i > 0 {
				fmt.Fprintf(&buf, ", ")
			}
			fmt.Fprintf(&buf, "0x%x", w)
		}
		fmt.Fprintf(&buf, "},\n")
	}
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "type scriptRange struct {\n\tlo, hi rune\n\tset    uint16\n}\n\n")
	fmt.Fprintf(&buf, "var scriptRanges = [...]scriptRange{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t{0x%X, 0x%X, %d},\n", e.lo, e.hi, e.set)
	}
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "// allowedRanges holds the Identifier_Status=Allowed set of UTS #39\n")
	fmt.Fprintf(&buf, "// section 3.1. Every other code point is Restricted.\n")
	fmt.Fprintf(&buf, "var allowedRanges = [...]struct{ lo, hi rune }{\n")
	for _, a := range allowed {
		fmt.Fprintf(&buf, "\t{0x%X, 0x%X},\n", a[0], a[1])
	}
	fmt.Fprintf(&buf, "}\n\n")

	// Table 5 of UAX #31. Since Unicode 17 Bopomofo is a Limited Use script
	// and is no longer in this list.
	recommended := []string{
		"Zyyy", "Zinh", "Arab", "Armn", "Beng", "Cyrl", "Deva", "Ethi", "Geor",
		"Grek", "Gujr", "Guru", "Hang", "Hani", "Hebr", "Hira", "Kana", "Knda",
		"Khmr", "Laoo", "Latn", "Mlym", "Mymr", "Orya", "Sinh", "Taml", "Telu",
		"Thaa", "Thai", "Tibt",
	}
	recSet := make([]uint64, words)
	for _, c := range recommended {
		i, ok := index[c]
		if !ok {
			log.Fatalf("recommended script %q is not a Script value", c)
		}
		recSet[i/64] |= 1 << uint(i%64)
	}
	fmt.Fprintf(&buf, "// recommendedSet is Table 5, Recommended Scripts of UAX #31.\n")
	fmt.Fprintf(&buf, "var recommendedSet = Set{[setWords]uint64{")
	for i, w := range recSet {
		if i > 0 {
			fmt.Fprintf(&buf, ", ")
		}
		fmt.Fprintf(&buf, "0x%x", w)
	}
	fmt.Fprintf(&buf, "}}\n\n")

	fmt.Fprintf(&buf, "// allSet is ALL: every script value this package knows.\n")
	fmt.Fprintf(&buf, "var allSet = Set{[setWords]uint64{")
	for i, w := range all {
		if i > 0 {
			fmt.Fprintf(&buf, ", ")
		}
		fmt.Fprintf(&buf, "0x%x", w)
	}
	fmt.Fprintf(&buf, "}}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile("tables.go.broken", buf.Bytes(), 0o644)
		log.Fatalf("format: %v (unformatted output in tables.go.broken)", err)
	}
	if err := os.WriteFile("tables.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote tables.go: %d scripts, %d distinct sets, %d ranges, %d allowed ranges",
		len(codes), len(pool), len(entries), len(allowed))
}

func fetch(url string) []byte {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatalf("get %s: %v", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("get %s: %s", url, resp.Status)
	}
	b, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("read %s: %v", url, err)
	}
	return b
}

// checkVersion fails if a security data file is not the pinned release. The
// security files live under .../security/latest/ because the versioned
// directory for this release is not published yet, so the header is the only
// thing tying them to a version.
func checkVersion(name string, data []byte) {
	for _, line := range strings.Split(string(data), "\n") {
		if v, ok := strings.CutPrefix(strings.TrimSpace(line), "# Version:"); ok {
			if got := strings.TrimSpace(v); got != unicodeVersion {
				log.Fatalf("%s is Unicode %s, want %s", name, got, unicodeVersion)
			}
			return
		}
	}
	log.Fatalf("%s has no # Version: header", name)
}

// parseAliases returns the Script property values in their four-letter form,
// and a map from the long name used by Scripts.txt to that form.
func parseAliases(data []byte) (codes []string, longToCode map[string]string) {
	longToCode = make(map[string]string)
	forEachLine(data, func(line string) {
		fields := splitFields(line)
		if len(fields) < 3 || fields[0] != "sc" {
			return
		}
		code, long := fields[1], fields[2]
		codes = append(codes, code)
		longToCode[long] = code
		// Later fields are additional aliases for the same value.
		for _, alias := range fields[3:] {
			longToCode[alias] = code
		}
	})
	sort.Strings(codes)
	return codes, longToCode
}

func parseScripts(data []byte, longToCode map[string]string) map[rune]string {
	out := make(map[rune]string)
	forEachLine(data, func(line string) {
		fields := splitFields(line)
		if len(fields) < 2 {
			return
		}
		lo, hi := parseRange(fields[0])
		code, ok := longToCode[fields[1]]
		if !ok {
			log.Fatalf("Scripts.txt: unknown script name %q", fields[1])
		}
		for r := lo; r <= hi; r++ {
			out[r] = code
		}
	})
	return out
}

func parseScriptExtensions(data []byte) map[rune][]string {
	out := make(map[rune][]string)
	forEachLine(data, func(line string) {
		fields := splitFields(line)
		if len(fields) < 2 {
			return
		}
		lo, hi := parseRange(fields[0])
		codes := strings.Fields(fields[1])
		for r := lo; r <= hi; r++ {
			out[r] = codes
		}
	})
	return out
}

func parseAllowed(data []byte) [][2]rune {
	var out [][2]rune
	forEachLine(data, func(line string) {
		fields := splitFields(line)
		if len(fields) < 2 || fields[1] != "Allowed" {
			return
		}
		lo, hi := parseRange(fields[0])
		if n := len(out); n > 0 && out[n-1][1] == lo-1 {
			out[n-1][1] = hi
			return
		}
		out = append(out, [2]rune{lo, hi})
	})
	return out
}

// forEachLine calls f for every line with the comment and trailing space
// stripped, skipping blanks.
func forEachLine(data []byte, f func(string)) {
	sc := bufio.NewScanner(bytes.NewReader(data))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if line = strings.TrimSpace(line); line == "" {
			continue
		}
		f(line)
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
}

func splitFields(line string) []string {
	parts := strings.Split(line, ";")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

func parseRange(s string) (lo, hi rune) {
	before, after, found := strings.Cut(s, "..")
	lo = parseHex(before)
	if !found {
		return lo, lo
	}
	return lo, parseHex(after)
}

func parseHex(s string) rune {
	v, err := strconv.ParseUint(strings.TrimSpace(s), 16, 32)
	if err != nil {
		log.Fatalf("bad code point %q: %v", s, err)
	}
	return rune(v)
}
